name: Publish dockerfile

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  publish-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        run: echo "::set-env name=VERSION::${GITHUB_REF##*/v}"

      - name: Build the docker container
        run: docker build -t docker.pkg.github.com/${GITHUB_REPOSITORY}/musescore-headless:${VERSION} .
      
      - name: Login to github packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u $(echo ${GITHUB_REPOSITORY} | awk -F/ '{print $1}') --password-stdin
      
      - name: Publish the docker container to github
        run: docker push docker.pkg.github.com/${GITHUB_REPOSITORY}/musescore-headless:${VERSION}

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Prepare the docker container for publishing to dockerhub
        run: docker tag docker.pkg.github.com/${GITHUB_REPOSITORY}/musescore-headless:${VERSION} ${{ secrets.DOCKERHUB_REPO_NAME} }}/musescore-headless:${VERSION}

      - name: Publish the docker container to docker hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME} }}/musescore-headless:${VERSION}
      